name: Deploy Quartz site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_WORKSPACE: ${{ github.workspace }}
      GIT_USER: "Github Actions [bot]"
      GIT_EMAIL: "actions@github.com"
      PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
    steps:
      - name: Echo Workspace
        run: |
          echo $GITHUB_WORKSPACE
          echo "Current WD:" $(pwd)
      - name: Show Tree
        run: |
          echo "🍿 Tree:"
          tree -L 2 -I "node_modules|docs|quartz"
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          repository: smaroukis/quartz
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: Custom User Prepare Site Scripts
        run: ./_userscripts/prebuild.sh
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.14
      - name: Install Dependencies
        run: npm ci
      - name: Echo Current Directory
        run: echo "Current WD:" $(pwd)
      - name: Build Quartz
        run: npx quartz build -o "public"
      - name: Show Tree
        run: |
          echo "🍿 Tree:"
          tree -L 2 -I "node_modules|docs|quartz"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: smaroukis/quartz
          publish_branch: gh-pages
          publish_dir: ${{ github.workspace }}/quartz/public
