name: Deploy Quartz site to GitHub Pages
 
on:
  push:
    branches:
      - main
 
permissions:
  contents: read
  pages: write
  id-token: write
 
concurrency:
  group: "pages"
  cancel-in-progress: false
 
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions: 
      contents: write
    env: 
        GITHUB_WORKSPACE: ${{ github.workspace }}
        GIT_USER: "Github Actions [bot]"
        GIT_EMAIL: "actions@github.com"
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          repository: smaroukis/quartz
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: Custom User Prepare Site Scripts
        run: ./_userscripts/prebuild.sh
      - uses: actions/setup-node@v3
        with:
          node-version: 18.14
      - name: Install Dependencies
        run: npm ci
      - name: Build Quartz
        run: npx quartz build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: public
 
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        external_repository: smaroukis/quartz
        publish_branch: gh-pages
        publish_dir: ./public